export interface CPUInstruction {
  opcode: number;
  name: string;
  implemented: boolean;
  description: string;
}

export class CPUInstructionChecker {
  private static instructions: Map<number, CPUInstruction> = new Map([
    [0x00, { opcode: 0x00, name: "NOP", implemented: true, description: "No operation" }],
    [0x01, { opcode: 0x01, name: "LD BC,nn", implemented: true, description: "Load 16-bit immediate into BC" }],
    [0x02, { opcode: 0x02, name: "LD (BC),A", implemented: true, description: "Load A into address pointed by BC" }],
    [0x03, { opcode: 0x03, name: "INC BC", implemented: true, description: "Increment BC" }],
    [0x04, { opcode: 0x04, name: "INC B", implemented: true, description: "Increment B" }],
    [0x05, { opcode: 0x05, name: "DEC B", implemented: true, description: "Decrement B" }],
    [0x06, { opcode: 0x06, name: "LD B,n", implemented: true, description: "Load 8-bit immediate into B" }],
    [0x07, { opcode: 0x07, name: "RLCA", implemented: true, description: "Rotate A left" }],
    [0x08, { opcode: 0x08, name: "LD (nn),SP", implemented: true, description: "Load SP into address nn" }],
    [0x09, { opcode: 0x09, name: "ADD HL,BC", implemented: true, description: "Add BC to HL" }],
    [0x0A, { opcode: 0x0A, name: "LD A,(BC)", implemented: true, description: "Load A from address pointed by BC" }],
    [0x0B, { opcode: 0x0B, name: "DEC BC", implemented: true, description: "Decrement BC" }],
    [0x0C, { opcode: 0x0C, name: "INC C", implemented: true, description: "Increment C" }],
    [0x0D, { opcode: 0x0D, name: "DEC C", implemented: true, description: "Decrement C" }],
    [0x0E, { opcode: 0x0E, name: "LD C,n", implemented: true, description: "Load 8-bit immediate into C" }],
    [0x0F, { opcode: 0x0F, name: "RRCA", implemented: true, description: "Rotate A right" }],
    [0x10, { opcode: 0x10, name: "STOP", implemented: true, description: "Stop the CPU" }],
    [0x11, { opcode: 0x11, name: "LD DE,nn", implemented: true, description: "Load 16-bit immediate into DE" }],
    [0x12, { opcode: 0x12, name: "LD (DE),A", implemented: true, description: "Load A into address pointed by DE" }],
    [0x13, { opcode: 0x13, name: "INC DE", implemented: true, description: "Increment DE" }],
    [0x14, { opcode: 0x14, name: "INC D", implemented: true, description: "Increment D" }],
    [0x15, { opcode: 0x15, name: "DEC D", implemented: true, description: "Decrement D" }],
    [0x16, { opcode: 0x16, name: "LD D,n", implemented: true, description: "Load 8-bit immediate into D" }],
    [0x17, { opcode: 0x17, name: "RLA", implemented: true, description: "Rotate A left through carry" }],
    [0x18, { opcode: 0x18, name: "JR n", implemented: true, description: "Relative jump by signed immediate" }],
    [0x19, { opcode: 0x19, name: "ADD HL,DE", implemented: true, description: "Add DE to HL" }],
    [0x1A, { opcode: 0x1A, name: "LD A,(DE)", implemented: true, description: "Load A from address pointed by DE" }],
    [0x1B, { opcode: 0x1B, name: "DEC DE", implemented: true, description: "Decrement DE" }],
    [0x1C, { opcode: 0x1C, name: "INC E", implemented: true, description: "Increment E" }],
    [0x1D, { opcode: 0x1D, name: "DEC E", implemented: true, description: "Decrement E" }],
    [0x1E, { opcode: 0x1E, name: "LD E,n", implemented: true, description: "Load 8-bit immediate into E" }],
    [0x1F, { opcode: 0x1F, name: "RRA", implemented: true, description: "Rotate A right through carry" }],
    [0x20, { opcode: 0x20, name: "JR NZ,n", implemented: true, description: "Relative jump by signed immediate if Z flag is reset" }],
    [0x21, { opcode: 0x21, name: "LD HL,nn", implemented: true, description: "Load 16-bit immediate into HL" }],
    [0x22, { opcode: 0x22, name: "LD (HL+),A", implemented: true, description: "Load A into address pointed by HL and increment HL" }],
    [0x23, { opcode: 0x23, name: "INC HL", implemented: true, description: "Increment HL" }],
    [0x24, { opcode: 0x24, name: "INC H", implemented: true, description: "Increment H" }],
    [0x25, { opcode: 0x25, name: "DEC H", implemented: true, description: "Decrement H" }],
    [0x26, { opcode: 0x26, name: "LD H,n", implemented: true, description: "Load 8-bit immediate into H" }],
    [0x27, { opcode: 0x27, name: "DAA", implemented: true, description: "Decimal adjust A" }],
    [0x28, { opcode: 0x28, name: "JR Z,n", implemented: true, description: "Relative jump by signed immediate if Z flag is set" }],
    [0x29, { opcode: 0x29, name: "ADD HL,HL", implemented: true, description: "Add HL to HL" }],
    [0x2A, { opcode: 0x2A, name: "LD A,(HL+)", implemented: true, description: "Load A from address pointed by HL and increment HL" }],
    [0x2B, { opcode: 0x2B, name: "DEC HL", implemented: true, description: "Decrement HL" }],
    [0x2C, { opcode: 0x2C, name: "INC L", implemented: true, description: "Increment L" }],
    [0x2D, { opcode: 0x2D, name: "DEC L", implemented: true, description: "Decrement L" }],
    [0x2E, { opcode: 0x2E, name: "LD L,n", implemented: true, description: "Load 8-bit immediate into L" }],
    [0x2F, { opcode: 0x2F, name: "CPL", implemented: true, description: "Complement A" }],
    [0x30, { opcode: 0x30, name: "JR NC,n", implemented: true, description: "Relative jump by signed immediate if C flag is reset" }],
    [0x31, { opcode: 0x31, name: "LD SP,nn", implemented: true, description: "Load 16-bit immediate into SP" }],
    [0x32, { opcode: 0x32, name: "LD (HL-),A", implemented: true, description: "Load A into address pointed by HL and decrement HL" }],
    [0x33, { opcode: 0x33, name: "INC SP", implemented: true, description: "Increment SP" }],
    [0x34, { opcode: 0x34, name: "INC (HL)", implemented: true, description: "Increment value at address pointed by HL" }],
    [0x35, { opcode: 0x35, name: "DEC (HL)", implemented: true, description: "Decrement value at address pointed by HL" }],
    [0x36, { opcode: 0x36, name: "LD (HL),n", implemented: true, description: "Load 8-bit immediate into address pointed by HL" }],
    [0x37, { opcode: 0x37, name: "SCF", implemented: true, description: "Set carry flag" }],
    [0x38, { opcode: 0x38, name: "JR C,n", implemented: true, description: "Relative jump by signed immediate if C flag is set" }],
    [0x39, { opcode: 0x39, name: "ADD HL,SP", implemented: true, description: "Add SP to HL" }],
    [0x3A, { opcode: 0x3A, name: "LD A,(HL-)", implemented: true, description: "Load A from address pointed by HL and decrement HL" }],
    [0x3B, { opcode: 0x3B, name: "DEC SP", implemented: true, description: "Decrement SP" }],
    [0x3C, { opcode: 0x3C, name: "INC A", implemented: true, description: "Increment A" }],
    [0x3D, { opcode: 0x3D, name: "DEC A", implemented: true, description: "Decrement A" }],
    [0x3E, { opcode: 0x3E, name: "LD A,n", implemented: true, description: "Load 8-bit immediate into A" }],
    [0x3F, { opcode: 0x3F, name: "CCF", implemented: true, description: "Complement carry flag" }],
    [0x40, { opcode: 0x40, name: "LD B,B", implemented: true, description: "Load B into B" }],
    [0x41, { opcode: 0x41, name: "LD B,C", implemented: true, description: "Load C into B" }],
    [0x42, { opcode: 0x42, name: "LD B,D", implemented: true, description: "Load D into B" }],
    [0x43, { opcode: 0x43, name: "LD B,E", implemented: true, description: "Load E into B" }],
    [0x44, { opcode: 0x44, name: "LD B,H", implemented: true, description: "Load H into B" }],
    [0x45, { opcode: 0x45, name: "LD B,L", implemented: true, description: "Load L into B" }],
    [0x46, { opcode: 0x46, name: "LD B,(HL)", implemented: true, description: "Load value at address HL into B" }],
    [0x47, { opcode: 0x47, name: "LD B,A", implemented: true, description: "Load A into B" }],
    [0x48, { opcode: 0x48, name: "LD C,B", implemented: true, description: "Load B into C" }],
    [0x49, { opcode: 0x49, name: "LD C,C", implemented: true, description: "Load C into C" }],
    [0x4A, { opcode: 0x4A, name: "LD C,D", implemented: true, description: "Load D into C" }],
    [0x4B, { opcode: 0x4B, name: "LD C,E", implemented: true, description: "Load E into C" }],
    [0x4C, { opcode: 0x4C, name: "LD C,H", implemented: true, description: "Load H into C" }],
    [0x4D, { opcode: 0x4D, name: "LD C,L", implemented: true, description: "Load L into C" }],
    [0x4E, { opcode: 0x4E, name: "LD C,(HL)", implemented: true, description: "Load value at address HL into C" }],
    [0x4F, { opcode: 0x4F, name: "LD C,A", implemented: true, description: "Load A into C" }],
    [0x50, { opcode: 0x50, name: "LD D,B", implemented: true, description: "Load B into D" }],
    [0x51, { opcode: 0x51, name: "LD D,C", implemented: true, description: "Load C into D" }],
    [0x52, { opcode: 0x52, name: "LD D,D", implemented: true, description: "Load D into D" }],
    [0x53, { opcode: 0x53, name: "LD D,E", implemented: true, description: "Load E into D" }],
    [0x54, { opcode: 0x54, name: "LD D,H", implemented: true, description: "Load H into D" }],
    [0x55, { opcode: 0x55, name: "LD D,L", implemented: true, description: "Load L into D" }],
    [0x56, { opcode: 0x56, name: "LD D,(HL)", implemented: true, description: "Load value at address HL into D" }],
    [0x57, { opcode: 0x57, name: "LD D,A", implemented: true, description: "Load A into D" }],
    [0x58, { opcode: 0x58, name: "LD E,B", implemented: true, description: "Load B into E" }],
    [0x59, { opcode: 0x59, name: "LD E,C", implemented: true, description: "Load C into E" }],
    [0x5A, { opcode: 0x5A, name: "LD E,D", implemented: true, description: "Load D into E" }],
    [0x5B, { opcode: 0x5B, name: "LD E,E", implemented: true, description: "Load E into E" }],
    [0x5C, { opcode: 0x5C, name: "LD E,H", implemented: true, description: "Load H into E" }],
    [0x5D, { opcode: 0x5D, name: "LD E,L", implemented: true, description: "Load L into E" }],
    [0x5E, { opcode: 0x5E, name: "LD E,(HL)", implemented: true, description: "Load value at address HL into E" }],
    [0x5F, { opcode: 0x5F, name: "LD E,A", implemented: true, description: "Load A into E" }],
    [0x60, { opcode: 0x60, name: "LD H,B", implemented: true, description: "Load B into H" }],
    [0x61, { opcode: 0x61, name: "LD H,C", implemented: true, description: "Load C into H" }],
    [0x62, { opcode: 0x62, name: "LD H,D", implemented: true, description: "Load D into H" }],
    [0x63, { opcode: 0x63, name: "LD H,E", implemented: true, description: "Load E into H" }],
    [0x64, { opcode: 0x64, name: "LD H,H", implemented: true, description: "Load H into H" }],
    [0x65, { opcode: 0x65, name: "LD H,L", implemented: true, description: "Load L into H" }],
    [0x66, { opcode: 0x66, name: "LD H,(HL)", implemented: true, description: "Load value at address HL into H" }],
    [0x67, { opcode: 0x67, name: "LD H,A", implemented: true, description: "Load A into H" }],
    [0x68, { opcode: 0x68, name: "LD L,B", implemented: true, description: "Load B into L" }],
    [0x69, { opcode: 0x69, name: "LD L,C", implemented: true, description: "Load C into L" }],
    [0x6A, { opcode: 0x6A, name: "LD L,D", implemented: true, description: "Load D into L" }],
    [0x6B, { opcode: 0x6B, name: "LD L,E", implemented: true, description: "Load E into L" }],
    [0x6C, { opcode: 0x6C, name: "LD L,H", implemented: true, description: "Load H into L" }],
    [0x6D, { opcode: 0x6D, name: "LD L,L", implemented: true, description: "Load L into L" }],
    [0x6E, { opcode: 0x6E, name: "LD L,(HL)", implemented: true, description: "Load value at address HL into L" }],
    [0x6F, { opcode: 0x6F, name: "LD L,A", implemented: true, description: "Load A into L" }],
    [0x70, { opcode: 0x70, name: "LD (HL),B", implemented: true, description: "Load B into address HL" }],
    [0x71, { opcode: 0x71, name: "LD (HL),C", implemented: true, description: "Load C into address HL" }],
    [0x72, { opcode: 0x72, name: "LD (HL),D", implemented: true, description: "Load D into address HL" }],
    [0x73, { opcode: 0x73, name: "LD (HL),E", implemented: true, description: "Load E into address HL" }],
    [0x74, { opcode: 0x74, name: "LD (HL),H", implemented: true, description: "Load H into address HL" }],
    [0x75, { opcode: 0x75, name: "LD (HL),L", implemented: true, description: "Load L into address HL" }],
    [0x76, { opcode: 0x76, name: "HALT", implemented: true, description: "Halt the CPU" }],
    [0x77, { opcode: 0x77, name: "LD (HL),A", implemented: true, description: "Load A into address HL" }],
    [0x78, { opcode: 0x78, name: "LD A,B", implemented: true, description: "Load B into A" }],
    [0x79, { opcode: 0x79, name: "LD A,C", implemented: true, description: "Load C into A" }],
    [0x7A, { opcode: 0x7A, name: "LD A,D", implemented: true, description: "Load D into A" }],
    [0x7B, { opcode: 0x7B, name: "LD A,E", implemented: true, description: "Load E into A" }],
    [0x7C, { opcode: 0x7C, name: "LD A,H", implemented: true, description: "Load H into A" }],
    [0x7D, { opcode: 0x7D, name: "LD A,L", implemented: true, description: "Load L into A" }],
    [0x7E, { opcode: 0x7E, name: "LD A,(HL)", implemented: true, description: "Load value at address HL into A" }],
    [0x7F, { opcode: 0x7F, name: "LD A,A", implemented: true, description: "Load A into A" }],
    [0x80, { opcode: 0x80, name: "ADD A,B", implemented: true, description: "Add B to A" }],
    [0x81, { opcode: 0x81, name: "ADD A,C", implemented: true, description: "Add C to A" }],
    [0x82, { opcode: 0x82, name: "ADD A,D", implemented: true, description: "Add D to A" }],
    [0x83, { opcode: 0x83, name: "ADD A,E", implemented: true, description: "Add E to A" }],
    [0x84, { opcode: 0x84, name: "ADD A,H", implemented: true, description: "Add H to A" }],
    [0x85, { opcode: 0x85, name: "ADD A,L", implemented: true, description: "Add L to A" }],
    [0x86, { opcode: 0x86, name: "ADD A,(HL)", implemented: true, description: "Add value at address HL to A" }],
    [0x87, { opcode: 0x87, name: "ADD A,A", implemented: true, description: "Add A to A" }],
    [0x88, { opcode: 0x88, name: "ADC A,B", implemented: true, description: "Add B + carry to A" }],
    [0x89, { opcode: 0x89, name: "ADC A,C", implemented: true, description: "Add C + carry to A" }],
    [0x8A, { opcode: 0x8A, name: "ADC A,D", implemented: true, description: "Add D + carry to A" }],
    [0x8B, { opcode: 0x8B, name: "ADC A,E", implemented: true, description: "Add E + carry to A" }],
    [0x8C, { opcode: 0x8C, name: "ADC A,H", implemented: true, description: "Add H + carry to A" }],
    [0x8D, { opcode: 0x8D, name: "ADC A,L", implemented: true, description: "Add L + carry to A" }],
    [0x8E, { opcode: 0x8E, name: "ADC A,(HL)", implemented: true, description: "Add value at address HL + carry to A" }],
    [0x8F, { opcode: 0x8F, name: "ADC A,A", implemented: true, description: "Add A + carry to A" }],
    [0x90, { opcode: 0x90, name: "SUB B", implemented: true, description: "Subtract B from A" }],
    [0x91, { opcode: 0x91, name: "SUB C", implemented: true, description: "Subtract C from A" }],
    [0x92, { opcode: 0x92, name: "SUB D", implemented: true, description: "Subtract D from A" }],
    [0x93, { opcode: 0x93, name: "SUB E", implemented: true, description: "Subtract E from A" }],
    [0x94, { opcode: 0x94, name: "SUB H", implemented: true, description: "Subtract H from A" }],
    [0x95, { opcode: 0x95, name: "SUB L", implemented: true, description: "Subtract L from A" }],
    [0x96, { opcode: 0x96, name: "SUB (HL)", implemented: true, description: "Subtract value at address HL from A" }],
    [0x97, { opcode: 0x97, name: "SUB A", implemented: true, description: "Subtract A from A" }],
    [0x98, { opcode: 0x98, name: "SBC A,B", implemented: true, description: "Subtract B + carry from A" }],
    [0x99, { opcode: 0x99, name: "SBC A,C", implemented: true, description: "Subtract C + carry from A" }],
    [0x9A, { opcode: 0x9A, name: "SBC A,D", implemented: true, description: "Subtract D + carry from A" }],
    [0x9B, { opcode: 0x9B, name: "SBC A,E", implemented: true, description: "Subtract E + carry from A" }],
    [0x9C, { opcode: 0x9C, name: "SBC A,H", implemented: true, description: "Subtract H + carry from A" }],
    [0x9D, { opcode: 0x9D, name: "SBC A,L", implemented: true, description: "Subtract L + carry from A" }],
    [0x9E, { opcode: 0x9E, name: "SBC A,(HL)", implemented: true, description: "Subtract value at address HL + carry from A" }],
    [0x9F, { opcode: 0x9F, name: "SBC A,A", implemented: true, description: "Subtract A + carry from A" }],
    [0xA0, { opcode: 0xA0, name: "AND B", implemented: true, description: "Logical AND B with A" }],
    [0xA1, { opcode: 0xA1, name: "AND C", implemented: true, description: "Logical AND C with A" }],
    [0xA2, { opcode: 0xA2, name: "AND D", implemented: true, description: "Logical AND D with A" }],
    [0xA3, { opcode: 0xA3, name: "AND E", implemented: true, description: "Logical AND E with A" }],
    [0xA4, { opcode: 0xA4, name: "AND H", implemented: true, description: "Logical AND H with A" }],
    [0xA5, { opcode: 0xA5, name: "AND L", implemented: true, description: "Logical AND L with A" }],
    [0xA6, { opcode: 0xA6, name: "AND (HL)", implemented: true, description: "Logical AND value at address HL with A" }],
    [0xA7, { opcode: 0xA7, name: "AND A", implemented: true, description: "Logical AND A with A" }],
    [0xA8, { opcode: 0xA8, name: "XOR B", implemented: true, description: "Logical XOR B with A" }],
    [0xA9, { opcode: 0xA9, name: "XOR C", implemented: true, description: "Logical XOR C with A" }],
    [0xAA, { opcode: 0xAA, name: "XOR D", implemented: true, description: "Logical XOR D with A" }],
    [0xAB, { opcode: 0xAB, name: "XOR E", implemented: true, description: "Logical XOR E with A" }],
    [0xAC, { opcode: 0xAC, name: "XOR H", implemented: true, description: "Logical XOR H with A" }],
    [0xAD, { opcode: 0xAD, name: "XOR L", implemented: true, description: "Logical XOR L with A" }],
    [0xAE, { opcode: 0xAE, name: "XOR (HL)", implemented: true, description: "Logical XOR value at address HL with A" }],
    [0xAF, { opcode: 0xAF, name: "XOR A", implemented: true, description: "Logical XOR A with A" }],
    [0xB0, { opcode: 0xB0, name: "OR B", implemented: true, description: "Logical OR B with A" }],
    [0xB1, { opcode: 0xB1, name: "OR C", implemented: true, description: "Logical OR C with A" }],
    [0xB2, { opcode: 0xB2, name: "OR D", implemented: true, description: "Logical OR D with A" }],
    [0xB3, { opcode: 0xB3, name: "OR E", implemented: true, description: "Logical OR E with A" }],
    [0xB4, { opcode: 0xB4, name: "OR H", implemented: true, description: "Logical OR H with A" }],
    [0xB5, { opcode: 0xB5, name: "OR L", implemented: true, description: "Logical OR L with A" }],
    [0xB6, { opcode: 0xB6, name: "OR (HL)", implemented: true, description: "Logical OR value at address HL with A" }],
    [0xB7, { opcode: 0xB7, name: "OR A", implemented: true, description: "Logical OR A with A" }],
    [0xB8, { opcode: 0xB8, name: "CP B", implemented: true, description: "Compare B with A" }],
    [0xB9, { opcode: 0xB9, name: "CP C", implemented: true, description: "Compare C with A" }],
    [0xBA, { opcode: 0xBA, name: "CP D", implemented: true, description: "Compare D with A" }],
    [0xBB, { opcode: 0xBB, name: "CP E", implemented: true, description: "Compare E with A" }],
    [0xBC, { opcode: 0xBC, name: "CP H", implemented: true, description: "Compare H with A" }],
    [0xBD, { opcode: 0xBD, name: "CP L", implemented: true, description: "Compare L with A" }],
    [0xBE, { opcode: 0xBE, name: "CP (HL)", implemented: true, description: "Compare value at address HL with A" }],
    [0xBF, { opcode: 0xBF, name: "CP A", implemented: true, description: "Compare A with A" }],
    [0xC0, { opcode: 0xC0, name: "RET NZ", implemented: true, description: "Return if Z flag is reset" }],
    [0xC1, { opcode: 0xC1, name: "POP BC", implemented: true, description: "Pop BC from stack" }],
    [0xC2, { opcode: 0xC2, name: "JP NZ,nn", implemented: true, description: "Jump to nn if Z flag is reset" }],
    [0xC3, { opcode: 0xC3, name: "JP nn", implemented: true, description: "Jump to nn" }],
    [0xC4, { opcode: 0xC4, name: "CALL NZ,nn", implemented: true, description: "Call address nn if Z flag is reset" }],
    [0xC5, { opcode: 0xC5, name: "PUSH BC", implemented: true, description: "Push BC onto stack" }],
    [0xC6, { opcode: 0xC6, name: "ADD A,n", implemented: true, description: "Add 8-bit immediate to A" }],
    [0xC7, { opcode: 0xC7, name: "RST 00H", implemented: true, description: "Call address 0x00" }],
    [0xC8, { opcode: 0xC8, name: "RET Z", implemented: true, description: "Return if Z flag is set" }],
    [0xC9, { opcode: 0xC9, name: "RET", implemented: true, description: "Return" }],
    [0xCA, { opcode: 0xCA, name: "JP Z,nn", implemented: true, description: "Jump to nn if Z flag is set" }],
    [0xCB, { opcode: 0xCB, name: "PREFIX CB", implemented: true, description: "CB prefix for extended instructions" }],
    [0xCC, { opcode: 0xCC, name: "CALL Z,nn", implemented: true, description: "Call address nn if Z flag is set" }],
    [0xCD, { opcode: 0xCD, name: "CALL nn", implemented: true, description: "Call address nn" }],
    [0xCE, { opcode: 0xCE, name: "ADC A,n", implemented: true, description: "Add 8-bit immediate + carry to A" }],
    [0xCF, { opcode: 0xCF, name: "RST 08H", implemented: true, description: "Call address 0x08" }],
    [0xD0, { opcode: 0xD0, name: "RET NC", implemented: true, description: "Return if C flag is reset" }],
    [0xD1, { opcode: 0xD1, name: "POP DE", implemented: true, description: "Pop DE from stack" }],
    [0xD2, { opcode: 0xD2, name: "JP NC,nn", implemented: true, description: "Jump to nn if C flag is reset" }],
    [0xD3, { opcode: 0xD3, name: "OUT (n),A", implemented: false, description: "Output A to port n (not implemented)" }],
    [0xD4, { opcode: 0xD4, name: "CALL NC,nn", implemented: true, description: "Call address nn if C flag is reset" }],
    [0xD5, { opcode: 0xD5, name: "PUSH DE", implemented: true, description: "Push DE onto stack" }],
    [0xD6, { opcode: 0xD6, name: "SUB n", implemented: true, description: "Subtract 8-bit immediate from A" }],
    [0xD7, { opcode: 0xD7, name: "RST 10H", implemented: true, description: "Call address 0x10" }],
    [0xD8, { opcode: 0xD8, name: "RET C", implemented: true, description: "Return if C flag is set" }],
    [0xD9, { opcode: 0xD9, name: "RETI", implemented: true, description: "Return and enable interrupts" }],
    [0xDA, { opcode: 0xDA, name: "JP C,nn", implemented: true, description: "Jump to nn if C flag is set" }],
    [0xDB, { opcode: 0xDB, name: "IN A,(n)", implemented: false, description: "Input from port n to A (not implemented)" }],
    [0xDC, { opcode: 0xDC, name: "CALL C,nn", implemented: true, description: "Call address nn if C flag is set" }],
    [0xDD, { opcode: 0xDD, name: "CALL nn", implemented: false, description: "Call address nn (not implemented)" }],
    [0xDE, { opcode: 0xDE, name: "SBC A,n", implemented: true, description: "Subtract 8-bit immediate + carry from A" }],
    [0xDF, { opcode: 0xDF, name: "RST 18H", implemented: true, description: "Call address 0x18" }],
    [0xE0, { opcode: 0xE0, name: "LDH (n),A", implemented: true, description: "Load A into address 0xFF00 + n" }],
    [0xE1, { opcode: 0xE1, name: "POP HL", implemented: true, description: "Pop HL from stack" }],
    [0xE2, { opcode: 0xE2, name: "LD (C),A", implemented: true, description: "Load A into address 0xFF00 + C" }],
    [0xE3, { opcode: 0xE3, name: "EX (SP),HL", implemented: false, description: "Exchange HL with value at SP (not implemented)" }],
    [0xE4, { opcode: 0xE4, name: "CALL PO,nn", implemented: false, description: "Call address nn if PO (not implemented)" }],
    [0xE5, { opcode: 0xE5, name: "PUSH HL", implemented: true, description: "Push HL onto stack" }],
    [0xE6, { opcode: 0xE6, name: "AND n", implemented: true, description: "Logical AND 8-bit immediate with A" }],
    [0xE7, { opcode: 0xE7, name: "RST 20H", implemented: true, description: "Call address 0x20" }],
    [0xE8, { opcode: 0xE8, name: "ADD SP,n", implemented: true, description: "Add signed 8-bit immediate to SP" }],
    [0xE9, { opcode: 0xE9, name: "JP (HL)", implemented: true, description: "Jump to address HL" }],
    [0xEA, { opcode: 0xEA, name: "LD (nn),A", implemented: true, description: "Load A into address nn" }],
    [0xEB, { opcode: 0xEB, name: "EX DE,HL", implemented: false, description: "Exchange DE with HL (not implemented)" }],
    [0xEC, { opcode: 0xEC, name: "CALL PE,nn", implemented: false, description: "Call address nn if PE (not implemented)" }],
    [0xEC, { opcode: 0xEC, name: "CALL PE,nn", implemented: false, description: "Call address nn if PE (not implemented)" }],
    [0xED, { opcode: 0xED, name: "CALL nn", implemented: false, description: "Call address nn (not implemented)" }],
    [0xEE, { opcode: 0xEE, name: "XOR n", implemented: true, description: "Logical XOR 8-bit immediate with A" }],
    [0xEF, { opcode: 0xEF, name: "RST 28H", implemented: true, description: "Call address 0x28" }],
    [0xF0, { opcode: 0xF0, name: "LDH A,(n)", implemented: true, description: "Load A from address 0xFF00 + n" }],
    [0xF1, { opcode: 0xF1, name: "POP AF", implemented: true, description: "Pop AF from stack" }],
    [0xF2, { opcode: 0xF2, name: "LD A,(C)", implemented: true, description: "Load A from address 0xFF00 + C" }],
    [0xF3, { opcode: 0xF3, name: "DI", implemented: true, description: "Disable interrupts" }],
    [0xF4, { opcode: 0xF4, name: "CALL P,nn", implemented: false, description: "Call address nn if P (not implemented)" }],
    [0xF5, { opcode: 0xF5, name: "PUSH AF", implemented: true, description: "Push AF onto stack" }],
    [0xF6, { opcode: 0xF6, name: "OR n", implemented: true, description: "Logical OR 8-bit immediate with A" }],
    [0xF7, { opcode: 0xF7, name: "RST 30H", implemented: true, description: "Call address 0x30" }],
    [0xF8, { opcode: 0xF8, name: "LD HL,SP+n", implemented: true, description: "Load SP + signed 8-bit immediate into HL" }],
    [0xF9, { opcode: 0xF9, name: "LD SP,HL", implemented: true, description: "Load HL into SP" }],
    [0xFA, { opcode: 0xFA, name: "LD A,(nn)", implemented: true, description: "Load A from address nn" }],
    [0xFB, { opcode: 0xFB, name: "EI", implemented: true, description: "Enable interrupts" }],
    [0xFC, { opcode: 0xFC, name: "CALL M,nn", implemented: false, description: "Call address nn if M (not implemented)" }],
    [0xFD, { opcode: 0xFD, name: "CALL nn", implemented: false, description: "Call address nn (not implemented)" }],
    [0xFE, { opcode: 0xFE, name: "CP n", implemented: true, description: "Compare 8-bit immediate with A" }],
    [0xFF, { opcode: 0xFF, name: "RST 38H", implemented: true, description: "Call address 0x38" }],
  ]);

  public static checkImplementation(opcode: number): CPUInstruction | undefined {
    return this.instructions.get(opcode);
  }

  public static getInstructionByName(name: string): CPUInstruction | undefined {
    for (const instruction of this.instructions.values()) {
      if (instruction.name === name) {
        return instruction;
      }
    }
    return undefined;
  }

  public static validateROM(romData: Uint8Array): { valid: boolean; errors: string[] } {
    const errors: string[] = [];
    const seenOpcodes = new Set<number>();

    // Scan first 256 bytes for common opcodes
    for (let i = 0; i < Math.min(romData.length, 256); i++) {
      const opcode = romData[i];
      if (!seenOpcodes.has(opcode)) {
        seenOpcodes.add(opcode);
        const instruction = this.checkImplementation(opcode);
        if (instruction && !instruction.implemented) {
          errors.push(`Unimplemented opcode 0x${opcode.toString(16).padStart(2, '0')} (${instruction.name})`);
        }
      }
    }

    return {
      valid: errors.length === 0,
      errors
    };
  }
}
